--------------------------------------------------------
--  文件已创建 - 星期三-一月-10-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCESS_TOKEN
--------------------------------------------------------

  CREATE TABLE "ACCESS_TOKEN" 
   (	"TOKEN_VALUE" VARCHAR2(1000 BYTE), 
	"EXPIRATION" DATE, 
	"TOKEN_TYPE" VARCHAR2(1000 BYTE), 
	"REFRESH_TOKEN_ID" NUMBER(20,0), 
	"CLIENT_ID" NVARCHAR2(200), 
	"AUTH_HOLDER_ID" NUMBER(20,0), 
	"APPROVED_SITE_ID" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ACCESS_TOKEN
SET DEFINE OFF;
